CREATE DATABASE IF NOT EXISTS burgers_db;

CREATE TABLE IF NOT EXISTS burgers (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    burger_name VARCHAR(100) NOT NULL,
    devoured BOOLEAN NOT NULL DEFAULT 0
);

